### ISSUE TITLE
Relax Minimum Python to 3.8

### ISSUE THREAD

**Issue by KyleKing** [tmr232/mdformat-wikilink#6]
Thanks for building this plugin! I would like to have WikiLinks formatted properly, but I need to support older versions of Python (`^3.8`).

Could you please consider making a new release that supports `^3.8`?

For now, my workaround has been to copy over the logic: https://github.com/KyleKing/mdformat-mkdocs/commit/5f686f1f3d461318673045b30ace574adedddb61

**Comment by tmr232** [comment]
Thanks for reaching out!

Should be solved with #7 . The new version is 0.2.0

**Comment by KyleKing** [comment]
Thanks!
